packages:
  - .
  - website/versions/*

allowBuilds:
  esbuild: true
  sharp: true
  '@parcel/watcher': true

minimumReleaseAgeExclude:
  - '@solidjs/babel-plugin@2.0.0-rc.9'
  - '@solidjs/compiler-darwin-arm64@2.0.0-rc.9'
  - '@solidjs/compiler-darwin-x64@2.0.0-rc.9'
  - '@solidjs/compiler-linux-arm64-gnu@2.0.0-rc.9'
  - '@solidjs/compiler-linux-x64-gnu@2.0.0-rc.9'
  - '@solidjs/compiler-wasm32-wasi@2.0.0-rc.9'
  - '@solidjs/compiler-win32-x64-msvc@2.0.0-rc.9'
  - '@solidjs/compiler@2.0.0-rc.9'
  - '@solidjs/vite-plugin@3.0.0-next.44'
  - '@solidjs/web@2.0.0-rc.9'
  - '@solidjs/signals@2.0.0-rc.9'
  - solid-js@2.0.0-rc.9
  - '@solidjs/router@2.0.0-next.26'

overrides:
  '@kobalte/core>solid-js': 2.0.0-rc.8
  '@kobalte/core>@solidjs/web': 2.0.0-rc.8
  '@kobalte/utils>solid-js': 2.0.0-rc.8
  '@kobalte/utils>@solidjs/web': 2.0.0-rc.8
